// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFkwRQVJRjN12vdDtvY_J62tGuXBX7JiY',
    appId: '1:332241203140:web:e01d02499a79053b31fe91',
    messagingSenderId: '332241203140',
    projectId: 'diutravelmate-cd9d9',
    authDomain: 'diutravelmate-cd9d9.firebaseapp.com',
    storageBucket: 'diutravelmate-cd9d9.firebasestorage.app',
    measurementId: 'G-SBCSZBVKS7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lhc0mFnZiNn-MBXmZ8n-v3c-U6DMMRg',
    appId: '1:332241203140:ios:d7319115d03fdd1e31fe91',
    messagingSenderId: '332241203140',
    projectId: 'diutravelmate-cd9d9',
    storageBucket: 'diutravelmate-cd9d9.firebasestorage.app',
    iosBundleId: 'com.example.tarvelMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lhc0mFnZiNn-MBXmZ8n-v3c-U6DMMRg',
    appId: '1:332241203140:ios:47b88d2bcf1dfe8b31fe91',
    messagingSenderId: '332241203140',
    projectId: 'diutravelmate-cd9d9',
    storageBucket: 'diutravelmate-cd9d9.firebasestorage.app',
    iosBundleId: 'com.example.diuTravelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFkwRQVJRjN12vdDtvY_J62tGuXBX7JiY',
    appId: '1:332241203140:web:073207cf9047e79931fe91',
    messagingSenderId: '332241203140',
    projectId: 'diutravelmate-cd9d9',
    authDomain: 'diutravelmate-cd9d9.firebaseapp.com',
    storageBucket: 'diutravelmate-cd9d9.firebasestorage.app',
    measurementId: 'G-KDQXN2TGGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHSMWSWuryQ8lok3leN5kYHkl5m1HcpMc',
    appId: '1:332241203140:android:194a354a614fc92a31fe91',
    messagingSenderId: '332241203140',
    projectId: 'diutravelmate-cd9d9',
    storageBucket: 'diutravelmate-cd9d9.firebasestorage.app',
  );

}